name: Auto Merge for Contributors

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Get PR author
        id: pr_author
        run: echo "author=$(jq -r .pull_request.user.login "$GITHUB_EVENT_PATH")" >> $GITHUB_OUTPUT

      - name: Check if user is a past contributor (merged PRs)
        id: check_contributor
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          author="${{ steps.pr_author.outputs.author }}"
          repo="${{ github.repository }}"

          # Check if the user has a merged PR in the past
          count=$(gh pr list --search "author:$author is:merged" --repo "$repo" --json number --jq "length")

          if [ "$count" -gt 0 ]; then
            echo "is_contributor=true" >> $GITHUB_OUTPUT
          else
            echo "is_contributor=false" >> $GITHUB_OUTPUT
          fi

      - name: Auto-merge PR
        if: steps.check_contributor.outputs.is_contributor == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge --repo ${{ github.repository }} --admin
